[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "audit-kernel"
version = "0.1.0"
description = "Stub audit-kernel distribution for Tessrax CI locking."
readme = "README.md"
requires-python = ">=3.10"
