repos:
  - repo: local
    hooks:
      - id: enforce-python-version
        name: Enforce Python 3.11 for pre-commit
        entry: python tools/precommit_python_version.py
        language: system
        pass_filenames: false
