name: Epistemic Meta Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  epistemic_meta_audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-lock.txt
          pip install -e .
      - name: Verify lock-file consistency
        run: diff <(pip freeze | sort) <(sort requirements-lock.txt)
        shell: bash
      - name: Run Epistemic Meta-Tests
        run: pytest -q tests/test_meta_audit.py
